// Housekeeping for clean layouts in keymap.c
#define ____    KC_TRNS
#define ACUT    SE_ACUT
#define ADIA    SE_ADIA
#define AMPR    SE_AMPR
#define ARNG    SE_ARNG
#define ASTR    KC_PAST
#define AT      SE_AT
#define BSLS    SE_BSLS
#define BSPC    KC_BSPC
#define CIRC    SE_CIRC
#define COLN    SE_COLN
#define COMM    SE_COMM
#define DEL     KC_DEL
#define DIAE    SE_DIAE
#define DLR     SE_DLR
#define DOT     SE_DOT
#define DQUO    SE_DQUO
#define END     KC_END
#define ENT     KC_ENT
#define EQL     KC_PEQL
#define ESC     KC_ESC
#define EXLM    SE_EXLM
#define GRV     SE_GRV
#define HASH    SE_HASH
#define HOME    KC_HOME
#define MINS    KC_PMNS
#define LABK    SE_LABK
#define LBRC    SE_LBRC
#define LCBR    SE_LCBR
#define LEFT    KC_LEFT
#define LPRN    SE_LPRN
#define ODIA    SE_ODIA
#define PERC    SE_PERC
#define PGDN    KC_PGDN
#define PGUP    KC_PGUP
#define PIPE    SE_PIPE
#define PLUS    KC_PPLS
#define QUES    SE_QUES
#define QUOT    SE_QUOT
#define RABK    SE_RABK
#define RBRC    SE_RBRC
#define RCBR    SE_RCBR
#define RGHT    KC_RGHT
#define RPRN    SE_RPRN
#define SCLN    SE_SCLN
#define SLSH    KC_PSLS
#define SPC     KC_SPC
#define TAB     KC_TAB
#define TILD    SE_TILD
#define UNDS    SE_UNDS
